sudo: required

services:
  - docker

script:  
  - docker build -t mayankgarg3101/react-main-demo .
  - docker images mayankgarg3101/react-main-demo

before_deploy:
  - docker login -u mayankgarg3101/ -p poiuy@9876

deploy:
  provider: script
  script: docker push mayankgarg3101/react-main-demo
  on:
    branch: master
  
      

  