version: '3.5'

services: 

  react-app:
    container_name: app-react
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - '.:/DockerExercise/example/src/app'
      - '/DockerExercise/example/src/app/node_modules'
    ports: 
      - '3000:3000'
    environment: 
      - Node_Env = development